"""sanctions screenings table

Revision ID: 26850d3b3a1a
Revises: 2a954c43407e
Create Date: 2026-06-08 03:57:49.656195
"""
from alembic import op
import sqlalchemy as sa


revision = '26850d3b3a1a'
down_revision = '2a954c43407e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanctions_screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('screened_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('band', sa.String(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Text(), nullable=False),
    sa.Column('sources_used', sa.Text(), nullable=False),
    sa.Column('screened_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctions_screenings_screening_id'), 'sanctions_screenings', ['screening_id'], unique=True)
    op.create_index(op.f('ix_sanctions_screenings_vendor_id'), 'sanctions_screenings', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sanctions_screenings_vendor_id'), table_name='sanctions_screenings')
    op.drop_index(op.f('ix_sanctions_screenings_screening_id'), table_name='sanctions_screenings')
    op.drop_table('sanctions_screenings')
    # ### end Alembic commands ###
