"""cert register supersession columns

Revision ID: 2a954c43407e
Revises: edf300a37e18
Create Date: 2026-06-07 15:36:36.763292
"""
from alembic import op
import sqlalchemy as sa


revision = '2a954c43407e'
down_revision = 'edf300a37e18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certifications', sa.Column('superseded', sa.Boolean(), nullable=False))
    op.add_column('certifications', sa.Column('artefact_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certifications', 'artefact_id')
    op.drop_column('certifications', 'superseded')
    # ### end Alembic commands ###
