"""monitoring_runs

Revision ID: 86f73604bd5b
Revises: ee5ab03cd1c0
Create Date: 2026-06-08 11:26:25.334098
"""
from alembic import op
import sqlalchemy as sa


revision = '86f73604bd5b'
down_revision = 'ee5ab03cd1c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('tasks', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_runs_run_id'), 'monitoring_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_monitoring_runs_started_at'), 'monitoring_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_runs_started_at'), table_name='monitoring_runs')
    op.drop_index(op.f('ix_monitoring_runs_run_id'), table_name='monitoring_runs')
    op.drop_table('monitoring_runs')
    # ### end Alembic commands ###
