"""baseline schema

Revision ID: edf300a37e18
Revises: 
Create Date: 2026-06-07 05:24:21.478533
"""
from alembic import op
import sqlalchemy as sa


revision = 'edf300a37e18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_learnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('issue', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.String(), nullable=True),
    sa.Column('used_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artefact_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artefact_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artefact_type', sa.String(), nullable=False),
    sa.Column('is_dated', sa.Boolean(), nullable=False),
    sa.Column('issue_date', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('object_uri', sa.String(), nullable=True),
    sa.Column('supersedes', sa.String(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('received_via', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artefact_id')
    )
    op.create_table('assessment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('inherent_band', sa.String(), nullable=True),
    sa.Column('residual_band', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('structured_json', sa.Text(), nullable=False),
    sa.Column('engagement_owner', sa.String(), nullable=True),
    sa.Column('spoc_name', sa.String(), nullable=True),
    sa.Column('spoc_email', sa.String(), nullable=True),
    sa.Column('spoc_office', sa.String(), nullable=True),
    sa.Column('spoc_user', sa.String(), nullable=True),
    sa.Column('assessor_user', sa.String(), nullable=True),
    sa.Column('assessor_signed_off', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=False),
    sa.Column('entry_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_country_code', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('mailing_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('engagement_id', sa.String(), nullable=True),
    sa.Column('parent_msa', sa.String(), nullable=True),
    sa.Column('primary_link', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('governing_law', sa.String(), nullable=True),
    sa.Column('effective_date', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('renewal_type', sa.String(), nullable=True),
    sa.Column('notice_period', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('terms_json', sa.Text(), nullable=False),
    sa.Column('gap_review', sa.Text(), nullable=True),
    sa.Column('clause_flags', sa.Text(), nullable=True),
    sa.Column('doc_link', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    op.create_table('criticality_designation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('overridden_by', sa.String(), nullable=True),
    sa.Column('designated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_addr', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_criticality_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('customer_impact', sa.Integer(), nullable=True),
    sa.Column('downtime_tolerance', sa.Integer(), nullable=True),
    sa.Column('alternative_availability', sa.Integer(), nullable=True),
    sa.Column('substitution_complexity', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id')
    )
    op.create_table('engagement_deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('accountable_owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_ext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('engagement_type', sa.String(), nullable=True),
    sa.Column('parent_engagement', sa.String(), nullable=True),
    sa.Column('related_engagements', sa.Text(), nullable=True),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('procurement_category', sa.String(), nullable=True),
    sa.Column('sourcing_route', sa.String(), nullable=True),
    sa.Column('competitive_flag', sa.String(), nullable=True),
    sa.Column('competitive_rationale', sa.Text(), nullable=True),
    sa.Column('requisition_ref', sa.String(), nullable=True),
    sa.Column('business_case_ref', sa.String(), nullable=True),
    sa.Column('contract_reference', sa.String(), nullable=True),
    sa.Column('agreement_type', sa.String(), nullable=True),
    sa.Column('signatories', sa.Text(), nullable=True),
    sa.Column('governing_law', sa.String(), nullable=True),
    sa.Column('governing_language', sa.String(), nullable=True),
    sa.Column('execution_date', sa.String(), nullable=True),
    sa.Column('effective_date', sa.String(), nullable=True),
    sa.Column('initial_term', sa.String(), nullable=True),
    sa.Column('renewal_type', sa.String(), nullable=True),
    sa.Column('renewal_window', sa.String(), nullable=True),
    sa.Column('notice_period', sa.String(), nullable=True),
    sa.Column('termination_rights', sa.String(), nullable=True),
    sa.Column('cure_period', sa.String(), nullable=True),
    sa.Column('change_of_control', sa.Boolean(), nullable=False),
    sa.Column('assignment_rights', sa.String(), nullable=True),
    sa.Column('clause_flags', sa.Text(), nullable=True),
    sa.Column('contract_status', sa.String(), nullable=True),
    sa.Column('contract_doc_link', sa.String(), nullable=True),
    sa.Column('contract_version', sa.String(), nullable=True),
    sa.Column('scope_in', sa.Text(), nullable=True),
    sa.Column('scope_out', sa.Text(), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('delivery_locations', sa.Text(), nullable=True),
    sa.Column('delivery_location', sa.String(), nullable=True),
    sa.Column('receiving_location', sa.String(), nullable=True),
    sa.Column('change_control_ref', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('supported_function', sa.String(), nullable=True),
    sa.Column('function_criticality', sa.String(), nullable=True),
    sa.Column('ict_flag', sa.String(), nullable=True),
    sa.Column('integration_points', sa.Text(), nullable=True),
    sa.Column('tcv', sa.Float(), nullable=True),
    sa.Column('acv', sa.Float(), nullable=True),
    sa.Column('pricing_model', sa.String(), nullable=True),
    sa.Column('rate_card', sa.Text(), nullable=True),
    sa.Column('indexation_terms', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('invoicing_frequency', sa.String(), nullable=True),
    sa.Column('discounts', sa.String(), nullable=True),
    sa.Column('fx_terms', sa.String(), nullable=True),
    sa.Column('budget_allocation', sa.String(), nullable=True),
    sa.Column('po_numbers', sa.Text(), nullable=True),
    sa.Column('goods_receipt_ref', sa.String(), nullable=True),
    sa.Column('invoice_refs', sa.Text(), nullable=True),
    sa.Column('committed_spend', sa.Float(), nullable=True),
    sa.Column('actual_spend', sa.Float(), nullable=True),
    sa.Column('performance_reporting_cadence', sa.String(), nullable=True),
    sa.Column('current_performance', sa.String(), nullable=True),
    sa.Column('sla_breach_history', sa.Text(), nullable=True),
    sa.Column('engagement_owner', sa.String(), nullable=True),
    sa.Column('vendor_account_manager', sa.String(), nullable=True),
    sa.Column('governance_forum', sa.String(), nullable=True),
    sa.Column('governance_cadence', sa.String(), nullable=True),
    sa.Column('escalation_path', sa.Text(), nullable=True),
    sa.Column('raci', sa.Text(), nullable=True),
    sa.Column('relationship_sentiment', sa.String(), nullable=True),
    sa.Column('data_classification', sa.String(), nullable=True),
    sa.Column('data_volume', sa.String(), nullable=True),
    sa.Column('personal_data', sa.Boolean(), nullable=False),
    sa.Column('data_subject_types', sa.Text(), nullable=True),
    sa.Column('system_access', sa.String(), nullable=True),
    sa.Column('physical_access', sa.Boolean(), nullable=False),
    sa.Column('mission_critical', sa.Boolean(), nullable=False),
    sa.Column('cross_border', sa.Boolean(), nullable=False),
    sa.Column('regulated_activity', sa.Boolean(), nullable=False),
    sa.Column('fourth_party_reliance', sa.Text(), nullable=True),
    sa.Column('concentration_contribution', sa.String(), nullable=True),
    sa.Column('rto', sa.String(), nullable=True),
    sa.Column('rpo', sa.String(), nullable=True),
    sa.Column('bcp_dependency', sa.String(), nullable=True),
    sa.Column('exit_plan', sa.Text(), nullable=True),
    sa.Column('exit_plan_tested', sa.Boolean(), nullable=False),
    sa.Column('transition_in_status', sa.String(), nullable=True),
    sa.Column('alternative_provider', sa.String(), nullable=True),
    sa.Column('dpa_in_place', sa.Boolean(), nullable=False),
    sa.Column('audit_rights', sa.Boolean(), nullable=False),
    sa.Column('audit_last_exercised', sa.String(), nullable=True),
    sa.Column('required_clauses_present', sa.String(), nullable=True),
    sa.Column('insurance_evidenced', sa.Boolean(), nullable=False),
    sa.Column('regulatory_notifications', sa.Text(), nullable=True),
    sa.Column('engagement_stage', sa.String(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('approver', sa.String(), nullable=True),
    sa.Column('approval_date', sa.String(), nullable=True),
    sa.Column('go_live_date', sa.String(), nullable=True),
    sa.Column('next_review_date', sa.String(), nullable=True),
    sa.Column('review_cadence', sa.String(), nullable=True),
    sa.Column('renewal_decision', sa.String(), nullable=True),
    sa.Column('renewal_decision_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('end_reason', sa.Text(), nullable=True),
    sa.Column('transition_status', sa.String(), nullable=True),
    sa.Column('data_steward', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('dq_completeness', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id')
    )
    op.create_table('engagement_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('acceptance', sa.Text(), nullable=True),
    sa.Column('payment_trigger', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('obligated_party', sa.String(), nullable=True),
    sa.Column('obl_type', sa.String(), nullable=False),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('recurrence', sa.String(), nullable=True),
    sa.Column('accountable_owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('consequence', sa.Text(), nullable=True),
    sa.Column('alert_rule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('key_personnel', sa.Boolean(), nullable=False),
    sa.Column('vetting_status', sa.String(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('jml_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('material_group_id', sa.String(), nullable=True),
    sa.Column('deployment_model', sa.String(), nullable=True),
    sa.Column('business_unit', sa.String(), nullable=True),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('assessment_id', sa.String(), nullable=True),
    sa.Column('annual_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('inherent_band', sa.String(), nullable=True),
    sa.Column('inherent_score', sa.Float(), nullable=True),
    sa.Column('residual_band', sa.String(), nullable=True),
    sa.Column('residual_score', sa.Float(), nullable=True),
    sa.Column('open_actions', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('owner_user', sa.String(), nullable=True),
    sa.Column('assigned_assessor', sa.String(), nullable=True),
    sa.Column('last_assessment_date', sa.String(), nullable=True),
    sa.Column('next_assessment_due', sa.String(), nullable=True),
    sa.Column('reassessment_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id')
    )
    op.create_table('engagement_slas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('measurement_window', sa.String(), nullable=True),
    sa.Column('calculation', sa.Text(), nullable=True),
    sa.Column('credit_penalty', sa.String(), nullable=True),
    sa.Column('current_value', sa.String(), nullable=True),
    sa.Column('breach_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exit_alternative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prequalified', sa.Boolean(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('viability', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_alternative_vendor_id'), 'exit_alternative', ['vendor_id'], unique=False)
    op.create_table('exit_dependency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('impact_tolerance', sa.String(), nullable=False),
    sa.Column('max_downtime', sa.String(), nullable=False),
    sa.Column('criticality', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_dependency_vendor_id'), 'exit_dependency', ['vendor_id'], unique=False)
    op.create_table('exit_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('test_date', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('participants', sa.String(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('lessons', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_test_vendor_id'), 'exit_test', ['vendor_id'], unique=False)
    op.create_table('exit_transition_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('rto', sa.String(), nullable=False),
    sa.Column('rpo', sa.String(), nullable=False),
    sa.Column('dependency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_transition_step_vendor_id'), 'exit_transition_step', ['vendor_id'], unique=False)
    op.create_table('exit_trigger_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_trigger_event_vendor_id'), 'exit_trigger_event', ['vendor_id'], unique=False)
    op.create_table('fin_monitor_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('last_signal', sa.String(), nullable=True),
    sa.Column('last_swept', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=True),
    sa.Column('engagement_id', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('assessor', sa.String(), nullable=True),
    sa.Column('suggested_remediation', sa.Text(), nullable=True),
    sa.Column('suggested_closure', sa.Text(), nullable=True),
    sa.Column('progress_notes', sa.Text(), nullable=False),
    sa.Column('attachments', sa.Text(), nullable=False),
    sa.Column('risk_accepted', sa.Boolean(), nullable=False),
    sa.Column('acceptance_expiry', sa.String(), nullable=True),
    sa.Column('acceptance_rationale', sa.Text(), nullable=True),
    sa.Column('accepted_by', sa.String(), nullable=True),
    sa.Column('raised_by', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('remediation_id', sa.String(), nullable=True),
    sa.Column('closed_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id')
    )
    op.create_table('fourth_party_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fourth_party_id', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('service_provided', sa.String(), nullable=True),
    sa.Column('hq_country', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('listing_status', sa.String(), nullable=True),
    sa.Column('concentration_flag', sa.Boolean(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fourth_party_id')
    )
    op.create_table('fourth_party_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fourth_party_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fourth_party_id', 'vendor_id')
    )
    op.create_table('id_counters',
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity')
    )
    op.create_table('incident_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('date_of_incident', sa.String(), nullable=True),
    sa.Column('reported_date', sa.String(), nullable=True),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('engagement_id', sa.String(), nullable=True),
    sa.Column('active_engagements', sa.Text(), nullable=False),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('customer_impacting', sa.Boolean(), nullable=False),
    sa.Column('impacts_client_org', sa.Boolean(), nullable=False),
    sa.Column('impact_description', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('root_cause_assessment', sa.Text(), nullable=True),
    sa.Column('risk_entry_needed', sa.Boolean(), nullable=False),
    sa.Column('risk_entry_ref', sa.String(), nullable=True),
    sa.Column('notes_log', sa.Text(), nullable=False),
    sa.Column('attachments', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('vendor_notified_at', sa.String(), nullable=True),
    sa.Column('notification_sla_hours', sa.Integer(), nullable=True),
    sa.Column('notification_compliant', sa.String(), nullable=True),
    sa.Column('contract_notification_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_table('industry_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.String(), nullable=False),
    sa.Column('sic_code', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_id')
    )
    op.create_table('issue_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('artefact_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('closed_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id')
    )
    op.create_table('material_group_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_group_id', sa.String(), nullable=False),
    sa.Column('unspsc_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_group_id')
    )
    op.create_table('methodology_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methodology_doc_doc_id'), 'methodology_doc', ['doc_id'], unique=False)
    op.create_table('methodology_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oss_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('ecosystem', sa.String(), nullable=True),
    sa.Column('purl', sa.String(), nullable=True),
    sa.Column('cpe', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('licence', sa.String(), nullable=True),
    sa.Column('licence_category', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('maintenance', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_band', sa.String(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('vendor_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oss_component_key'), 'oss_component', ['key'], unique=True)
    op.create_index(op.f('ix_oss_component_name'), 'oss_component', ['name'], unique=False)
    op.create_index(op.f('ix_oss_component_purl'), 'oss_component', ['purl'], unique=False)
    op.create_table('oss_sbom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('product_version', sa.String(), nullable=True),
    sa.Column('fmt', sa.String(), nullable=True),
    sa.Column('spec_version', sa.String(), nullable=True),
    sa.Column('sbom_type', sa.String(), nullable=True),
    sa.Column('component_count', sa.Integer(), nullable=False),
    sa.Column('ntia_score', sa.Float(), nullable=True),
    sa.Column('quality_label', sa.String(), nullable=True),
    sa.Column('source_channel', sa.String(), nullable=True),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oss_sbom_engagement_id'), 'oss_sbom', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_oss_sbom_vendor_id'), 'oss_sbom', ['vendor_id'], unique=False)
    op.create_table('oss_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('sbom_id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('dep_type', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oss_usage_component_id'), 'oss_usage', ['component_id'], unique=False)
    op.create_index(op.f('ix_oss_usage_engagement_id'), 'oss_usage', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_oss_usage_sbom_id'), 'oss_usage', ['sbom_id'], unique=False)
    op.create_index(op.f('ix_oss_usage_vendor_id'), 'oss_usage', ['vendor_id'], unique=False)
    op.create_table('oss_vuln',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('cve', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('epss', sa.Float(), nullable=True),
    sa.Column('kev', sa.Boolean(), nullable=False),
    sa.Column('vex_status', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oss_vuln_component_id'), 'oss_vuln', ['component_id'], unique=False)
    op.create_index(op.f('ix_oss_vuln_cve'), 'oss_vuln', ['cve'], unique=False)
    op.create_table('perf_enrolment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('enrolled', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('enrolled_by', sa.String(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('performance_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('scorecard_id', sa.String(), nullable=True),
    sa.Column('review_date', sa.String(), nullable=True),
    sa.Column('cadence', sa.String(), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('outcomes', sa.Text(), nullable=True),
    sa.Column('vendor_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('vendor_ack_date', sa.String(), nullable=True),
    sa.Column('next_review_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('pestle_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('base_json', sa.Text(), nullable=True),
    sa.Column('vector_json', sa.Text(), nullable=True),
    sa.Column('cats_json', sa.Text(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('top_json', sa.Text(), nullable=True),
    sa.Column('movers_json', sa.Text(), nullable=True),
    sa.Column('refreshed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id')
    )
    op.create_index(op.f('ix_pestle_profile_entity_id'), 'pestle_profile', ['entity_id'], unique=False)
    op.create_table('remediation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remediation_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('target_date', sa.String(), nullable=True),
    sa.Column('milestones_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('completed_date', sa.String(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remediation_id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('scorecard_dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scorecard_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scorecard_kpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scorecard_id', sa.String(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('window', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('actual', sa.String(), nullable=True),
    sa.Column('auto_value', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('exclude_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stored_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data_b64', sa.Text(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('engagement_id', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=True)
    op.create_table('vendor_cyber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('certifications_json', sa.Text(), nullable=False),
    sa.Column('assurance_status', sa.String(), nullable=True),
    sa.Column('external_rating', sa.String(), nullable=True),
    sa.Column('external_rating_date', sa.String(), nullable=True),
    sa.Column('pentest_recency', sa.String(), nullable=True),
    sa.Column('breach_history_flag', sa.Boolean(), nullable=False),
    sa.Column('security_contact', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('vendor_esg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('esg_rating', sa.String(), nullable=True),
    sa.Column('esg_rating_source', sa.String(), nullable=True),
    sa.Column('scope3_sbt_status', sa.String(), nullable=True),
    sa.Column('environmental_certs', sa.Text(), nullable=True),
    sa.Column('labour_audit_findings', sa.Text(), nullable=True),
    sa.Column('diversity_classification', sa.String(), nullable=True),
    sa.Column('conflict_minerals_exposure', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('vendor_exit_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('exit_mode', sa.String(), nullable=False),
    sa.Column('strategy_type', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('target_window', sa.String(), nullable=False),
    sa.Column('impact_summary', sa.Text(), nullable=False),
    sa.Column('data_plan', sa.Text(), nullable=False),
    sa.Column('comms_plan', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('approver', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('one_off_cost', sa.Float(), nullable=True),
    sa.Column('dual_running_cost', sa.Float(), nullable=True),
    sa.Column('penalty_cost', sa.Float(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=False),
    sa.Column('readiness_band', sa.String(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=True),
    sa.Column('last_tested', sa.DateTime(), nullable=True),
    sa.Column('next_test_due', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_exit_plan_plan_id'), 'vendor_exit_plan', ['plan_id'], unique=False)
    op.create_index(op.f('ix_vendor_exit_plan_vendor_id'), 'vendor_exit_plan', ['vendor_id'], unique=False)
    op.create_table('vendor_governance_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('source_of_truth', sa.String(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('duplicate_cluster_id', sa.String(), nullable=True),
    sa.Column('data_steward', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.Column('dq_completeness', sa.Float(), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('consent_basis', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('lifecycle_state', sa.String(), nullable=False),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('approver', sa.String(), nullable=True),
    sa.Column('offboarding_date', sa.String(), nullable=True),
    sa.Column('offboarding_reason', sa.Text(), nullable=True),
    sa.Column('do_not_use_flag', sa.Boolean(), nullable=False),
    sa.Column('do_not_use_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('vendor_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_company', sa.String(), nullable=True),
    sa.Column('ai_assigned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    op.create_table('vendor_industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('industry_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'industry_id')
    )
    op.create_table('vendor_insurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('policy_type', sa.String(), nullable=False),
    sa.Column('coverage_limit', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('insurer', sa.String(), nullable=True),
    sa.Column('certificate_expiry', sa.String(), nullable=True),
    sa.Column('named_insured_verified', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_master_ext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('euid', sa.String(), nullable=True),
    sa.Column('erp_id', sa.String(), nullable=True),
    sa.Column('sourcing_id', sa.String(), nullable=True),
    sa.Column('grc_id', sa.String(), nullable=True),
    sa.Column('dba_names', sa.Text(), nullable=True),
    sa.Column('previous_names', sa.Text(), nullable=True),
    sa.Column('operating_status', sa.String(), nullable=True),
    sa.Column('immediate_parent', sa.String(), nullable=True),
    sa.Column('subsidiaries', sa.Text(), nullable=True),
    sa.Column('ubo_json', sa.Text(), nullable=False),
    sa.Column('ownership_type', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('sic_code', sa.String(), nullable=True),
    sa.Column('unspsc_code', sa.String(), nullable=True),
    sa.Column('nace_naics', sa.String(), nullable=True),
    sa.Column('supplier_category', sa.String(), nullable=True),
    sa.Column('segmentation', sa.String(), nullable=True),
    sa.Column('spend_band', sa.String(), nullable=True),
    sa.Column('sole_source', sa.Boolean(), nullable=False),
    sa.Column('substitutability', sa.String(), nullable=True),
    sa.Column('relationship_owner', sa.String(), nullable=True),
    sa.Column('sponsoring_bu', sa.String(), nullable=True),
    sa.Column('cost_centre', sa.String(), nullable=True),
    sa.Column('strategic_importance', sa.String(), nullable=True),
    sa.Column('business_dependency', sa.Text(), nullable=True),
    sa.Column('relationship_health', sa.String(), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('remittance_address', sa.Text(), nullable=True),
    sa.Column('operating_address', sa.Text(), nullable=True),
    sa.Column('service_countries', sa.Text(), nullable=True),
    sa.Column('data_locations', sa.Text(), nullable=True),
    sa.Column('offshore_flag', sa.Boolean(), nullable=False),
    sa.Column('geopolitical_risk', sa.String(), nullable=True),
    sa.Column('sanctions_jurisdiction_exposure', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('annual_spend', sa.Float(), nullable=True),
    sa.Column('spend_trend', sa.String(), nullable=True),
    sa.Column('discount_terms', sa.String(), nullable=True),
    sa.Column('credit_rating', sa.String(), nullable=True),
    sa.Column('credit_rating_date', sa.String(), nullable=True),
    sa.Column('financial_health_band', sa.String(), nullable=True),
    sa.Column('going_concern_flag', sa.Boolean(), nullable=False),
    sa.Column('vat_number', sa.String(), nullable=True),
    sa.Column('w_form_status', sa.String(), nullable=True),
    sa.Column('tax_residency', sa.String(), nullable=True),
    sa.Column('regulatory_licences', sa.Text(), nullable=True),
    sa.Column('regulated_entity', sa.Boolean(), nullable=False),
    sa.Column('bank_account_name', sa.String(), nullable=True),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('swift_bic', sa.String(), nullable=True),
    sa.Column('routing_number', sa.String(), nullable=True),
    sa.Column('bank_verified', sa.Boolean(), nullable=False),
    sa.Column('bank_verified_date', sa.String(), nullable=True),
    sa.Column('bank_change_locked', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('vendor_monitor_signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('captured_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_privacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('processes_personal_data', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('dpa_in_place', sa.Boolean(), nullable=False),
    sa.Column('data_categories', sa.Text(), nullable=True),
    sa.Column('data_subject_types', sa.Text(), nullable=True),
    sa.Column('transfer_mechanism', sa.String(), nullable=True),
    sa.Column('subprocessor_list_maintained', sa.Boolean(), nullable=False),
    sa.Column('ropa_reference', sa.String(), nullable=True),
    sa.Column('retention_terms', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('vendor_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('trading_name', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('duns', sa.String(), nullable=True),
    sa.Column('lei', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('incorporation_country', sa.String(), nullable=True),
    sa.Column('incorporation_date', sa.String(), nullable=True),
    sa.Column('legal_form', sa.String(), nullable=True),
    sa.Column('listing_status', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('ultimate_parent', sa.String(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.Float(), nullable=True),
    sa.Column('revenue_currency', sa.String(), nullable=True),
    sa.Column('hq_address', sa.Text(), nullable=True),
    sa.Column('hq_country', sa.String(), nullable=True),
    sa.Column('operating_countries', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('criticality_reason', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('onboarded_date', sa.String(), nullable=True),
    sa.Column('procurement_ref', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.Column('fourth_party_id', sa.String(), nullable=True),
    sa.Column('created_via', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('vendor_resilience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('supports_critical_function', sa.Boolean(), nullable=False),
    sa.Column('nth_party_json', sa.Text(), nullable=False),
    sa.Column('shared_upstream_flags', sa.Text(), nullable=True),
    sa.Column('spof_flag', sa.Boolean(), nullable=False),
    sa.Column('concentration_indicator', sa.Integer(), nullable=True),
    sa.Column('bcp_in_place', sa.Boolean(), nullable=False),
    sa.Column('bcp_last_tested', sa.String(), nullable=True),
    sa.Column('bcp_test_result', sa.String(), nullable=True),
    sa.Column('exit_plan_documented', sa.Boolean(), nullable=False),
    sa.Column('exit_plan_tested', sa.Boolean(), nullable=False),
    sa.Column('exit_plan_tested_date', sa.String(), nullable=True),
    sa.Column('rto', sa.String(), nullable=True),
    sa.Column('rpo', sa.String(), nullable=True),
    sa.Column('alternative_provider', sa.String(), nullable=True),
    sa.Column('portability_status', sa.String(), nullable=True),
    sa.Column('switching_cost', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('vendor_risk_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('inherent_band', sa.String(), nullable=True),
    sa.Column('residual_band', sa.String(), nullable=True),
    sa.Column('open_findings', sa.Integer(), nullable=False),
    sa.Column('max_severity', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('last_assessment', sa.String(), nullable=True),
    sa.Column('next_assessment_due', sa.String(), nullable=True),
    sa.Column('monitoring_signal', sa.String(), nullable=True),
    sa.Column('reputation_summary', sa.String(), nullable=True),
    sa.Column('sla_summary', sa.String(), nullable=True),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('dispute_history', sa.Text(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('review_cadence', sa.String(), nullable=True),
    sa.Column('last_review', sa.String(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_scorecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scorecard_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('period_label', sa.String(), nullable=False),
    sa.Column('period_start', sa.String(), nullable=True),
    sa.Column('period_end', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('band', sa.String(), nullable=True),
    sa.Column('review_cadence', sa.String(), nullable=False),
    sa.Column('critical_engagements', sa.Text(), nullable=True),
    sa.Column('agreed_with_vendor', sa.Boolean(), nullable=False),
    sa.Column('agreed_date', sa.String(), nullable=True),
    sa.Column('agreed_party', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_by', sa.String(), nullable=True),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scorecard_id')
    )
    op.create_table('vendor_screening',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('screen_type', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('screened_date', sa.String(), nullable=True),
    sa.Column('next_due', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_entity', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('critical_reason', sa.Text(), nullable=True),
    sa.Column('critical_by', sa.String(), nullable=True),
    sa.Column('critical_at', sa.DateTime(), nullable=True),
    sa.Column('ext_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fourth_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('concentration_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intel_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('band', sa.String(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('sweep_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('perm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perm_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'perm_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('inherent_band', sa.String(), nullable=True),
    sa.Column('inherent_pct', sa.Float(), nullable=True),
    sa.Column('residual_band', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('business_contact_name', sa.String(), nullable=True),
    sa.Column('business_contact_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('accepted_by', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('terms_json', sa.Text(), nullable=False),
    sa.Column('gap_review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('active_agent', sa.String(), nullable=False),
    sa.Column('dossier_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('object_uri', sa.String(), nullable=True),
    sa.Column('next_validation', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reassessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_messages')
    op.drop_table('background_insights')
    op.drop_table('reassessments')
    op.drop_table('offboarding')
    op.drop_table('findings')
    op.drop_table('documents')
    op.drop_table('conversation_sessions')
    op.drop_table('contracts')
    op.drop_table('acceptances')
    op.drop_table('engagements')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('monitoring')
    op.drop_table('intel_results')
    op.drop_table('incidents')
    op.drop_table('fourth_parties')
    op.drop_table('certifications')
    op.drop_table('webhooks')
    op.drop_table('vendors')
    op.drop_table('vendor_screening')
    op.drop_table('vendor_scorecard')
    op.drop_table('vendor_risk_profile')
    op.drop_table('vendor_resilience')
    op.drop_table('vendor_records')
    op.drop_table('vendor_privacy')
    op.drop_table('vendor_monitor_signal')
    op.drop_table('vendor_master_ext')
    op.drop_table('vendor_insurance')
    op.drop_table('vendor_industries')
    op.drop_table('vendor_groups')
    op.drop_table('vendor_governance_meta')
    op.drop_index(op.f('ix_vendor_exit_plan_vendor_id'), table_name='vendor_exit_plan')
    op.drop_index(op.f('ix_vendor_exit_plan_plan_id'), table_name='vendor_exit_plan')
    op.drop_table('vendor_exit_plan')
    op.drop_table('vendor_esg')
    op.drop_table('vendor_cyber')
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_table('stored_documents')
    op.drop_table('scorecard_kpi')
    op.drop_table('scorecard_dimension')
    op.drop_table('roles')
    op.drop_table('remediation_records')
    op.drop_index(op.f('ix_pestle_profile_entity_id'), table_name='pestle_profile')
    op.drop_table('pestle_profile')
    op.drop_table('permissions')
    op.drop_table('performance_review')
    op.drop_table('perf_enrolment')
    op.drop_index(op.f('ix_oss_vuln_cve'), table_name='oss_vuln')
    op.drop_index(op.f('ix_oss_vuln_component_id'), table_name='oss_vuln')
    op.drop_table('oss_vuln')
    op.drop_index(op.f('ix_oss_usage_vendor_id'), table_name='oss_usage')
    op.drop_index(op.f('ix_oss_usage_sbom_id'), table_name='oss_usage')
    op.drop_index(op.f('ix_oss_usage_engagement_id'), table_name='oss_usage')
    op.drop_index(op.f('ix_oss_usage_component_id'), table_name='oss_usage')
    op.drop_table('oss_usage')
    op.drop_index(op.f('ix_oss_sbom_vendor_id'), table_name='oss_sbom')
    op.drop_index(op.f('ix_oss_sbom_engagement_id'), table_name='oss_sbom')
    op.drop_table('oss_sbom')
    op.drop_index(op.f('ix_oss_component_purl'), table_name='oss_component')
    op.drop_index(op.f('ix_oss_component_name'), table_name='oss_component')
    op.drop_index(op.f('ix_oss_component_key'), table_name='oss_component')
    op.drop_table('oss_component')
    op.drop_table('notifications')
    op.drop_table('methodology_versions')
    op.drop_index(op.f('ix_methodology_doc_doc_id'), table_name='methodology_doc')
    op.drop_table('methodology_doc')
    op.drop_table('material_group_master')
    op.drop_table('issue_records')
    op.drop_table('industry_master')
    op.drop_table('incident_records')
    op.drop_table('id_counters')
    op.drop_table('fourth_party_vendors')
    op.drop_table('fourth_party_records')
    op.drop_table('finding_records')
    op.drop_table('fin_monitor_records')
    op.drop_index(op.f('ix_exit_trigger_event_vendor_id'), table_name='exit_trigger_event')
    op.drop_table('exit_trigger_event')
    op.drop_index(op.f('ix_exit_transition_step_vendor_id'), table_name='exit_transition_step')
    op.drop_table('exit_transition_step')
    op.drop_index(op.f('ix_exit_test_vendor_id'), table_name='exit_test')
    op.drop_table('exit_test')
    op.drop_index(op.f('ix_exit_dependency_vendor_id'), table_name='exit_dependency')
    op.drop_table('exit_dependency')
    op.drop_index(op.f('ix_exit_alternative_vendor_id'), table_name='exit_alternative')
    op.drop_table('exit_alternative')
    op.drop_table('engagement_slas')
    op.drop_table('engagement_records')
    op.drop_table('engagement_personnel')
    op.drop_table('engagement_obligations')
    op.drop_table('engagement_milestones')
    op.drop_table('engagement_ext')
    op.drop_table('engagement_deliverables')
    op.drop_table('engagement_criticality_input')
    op.drop_table('email_outbox')
    op.drop_table('criticality_designation')
    op.drop_table('contract_records')
    op.drop_table('contact_records')
    op.drop_table('audit_log')
    op.drop_table('assessment_records')
    op.drop_table('artefact_records')
    op.drop_table('ai_feedback')
    op.drop_table('agent_learnings')
    # ### end Alembic commands ###
