"""vendor_persons + watchlist_entries

Revision ID: ee5ab03cd1c0
Revises: 26850d3b3a1a
Create Date: 2026-06-08 08:43:55.282761
"""
from alembic import op
import sqlalchemy as sa


revision = 'ee5ab03cd1c0'
down_revision = '26850d3b3a1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('ownership_pct', sa.Float(), nullable=True),
    sa.Column('is_ubo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_persons_person_id'), 'vendor_persons', ['person_id'], unique=True)
    op.create_index(op.f('ix_vendor_persons_vendor_id'), 'vendor_persons', ['vendor_id'], unique=False)
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('list_name', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_entries_ext_id'), 'watchlist_entries', ['ext_id'], unique=False)
    op.create_index(op.f('ix_watchlist_entries_source'), 'watchlist_entries', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_entries_source'), table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_ext_id'), table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    op.drop_index(op.f('ix_vendor_persons_vendor_id'), table_name='vendor_persons')
    op.drop_index(op.f('ix_vendor_persons_person_id'), table_name='vendor_persons')
    op.drop_table('vendor_persons')
    # ### end Alembic commands ###
