"""engagement escrow fields

Revision ID: f3c0b3726465
Revises: 86f73604bd5b
Create Date: 2026-06-08 13:08:03.450257
"""
from alembic import op
import sqlalchemy as sa


revision = 'f3c0b3726465'
down_revision = '86f73604bd5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_ext', sa.Column('escrow_required', sa.Boolean(), nullable=False))
    op.add_column('engagement_ext', sa.Column('escrow_type', sa.String(), nullable=True))
    op.add_column('engagement_ext', sa.Column('escrow_agent', sa.String(), nullable=True))
    op.add_column('engagement_ext', sa.Column('escrow_agreement_ref', sa.String(), nullable=True))
    op.add_column('engagement_ext', sa.Column('escrow_status', sa.String(), nullable=True))
    op.add_column('engagement_ext', sa.Column('escrow_amount', sa.String(), nullable=True))
    op.add_column('engagement_ext', sa.Column('escrow_deposit_frequency', sa.String(), nullable=True))
    op.add_column('engagement_ext', sa.Column('escrow_release_conditions', sa.Text(), nullable=True))
    op.add_column('engagement_ext', sa.Column('escrow_last_verified', sa.String(), nullable=True))
    op.add_column('engagement_ext', sa.Column('escrow_beneficiaries', sa.String(), nullable=True))
    op.add_column('engagement_ext', sa.Column('escrow_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement_ext', 'escrow_notes')
    op.drop_column('engagement_ext', 'escrow_beneficiaries')
    op.drop_column('engagement_ext', 'escrow_last_verified')
    op.drop_column('engagement_ext', 'escrow_release_conditions')
    op.drop_column('engagement_ext', 'escrow_deposit_frequency')
    op.drop_column('engagement_ext', 'escrow_amount')
    op.drop_column('engagement_ext', 'escrow_status')
    op.drop_column('engagement_ext', 'escrow_agreement_ref')
    op.drop_column('engagement_ext', 'escrow_agent')
    op.drop_column('engagement_ext', 'escrow_type')
    op.drop_column('engagement_ext', 'escrow_required')
    # ### end Alembic commands ###
